<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>

<link href="stylesheets/com.quirky.contentd6df.css?1303335970" media="screen" rel="stylesheet" type="text/css" />

<link href="stylesheets/com.quirky.extrad6df.css?1303335970" media="screen" rel="stylesheet" type="text/css" />
<link href="stylesheets/com.tc.toolsd6df.css?1303335970" media="screen" rel="stylesheet" type="text/css" />

</head>

<div class="invent-faq box">
<div class="hd">
<h3>How does it work?</h3>
</div>
<div class="bd">
<h2 class="light-sans dark-blue">Here's the breakdown:</h2>
			

<div class="box-element">
<h4>Influence is a real-time measure of your contributions to a project.</h4>
<p style="font-size:14px; color:#666666">You can earn influence either by submitting a winning idea, or by supporting and refining that idea.</p>
</div>
<div class="box-element">
<h4>So how does it all work?</h4>
<p style="font-size:14px; color:#666666">Think of the Quirky influence engine as a complicated, evolving recipe, made up of many different ingredients. The ingredients are your contributions to the site, which include:</p>
<p style="font-size:14px; color:#666666">Submitting a winning product idea</p>
<p style="font-size:14px; color:#666666">Submitting a winning idea in another project</p>
<p style="font-size:14px; color:#666666">Voting for a winning idea</p>

<p style="font-size:14px; color:#666666">Rating the majority of ideas in a product evaluation round</p>
<p style="font-size:14px; color:#666666">Participating in a product research project</p>
<p style="font-size:14px; color:#666666">Committing to a product in presale</p>
<p style="font-size:14px; color:#666666">... and more.</p>
<p style="font-size:14px; color:#666666">All of these actions influence the final product in various ways and can earn you a percentage of the profits. </p>
</div> 
<div class="box-element">
<h4>Keep in mind that there’s no hard-and-fast rule or guarantee for earning influence.</h4>
<p style="font-size:14px; color:#666666">Influence is awarded at the sole discretion of Quirky’s platform and team. A user’s influence earnings in a given project depends on many factors: the number of phases in the project, the number of people who contributed to those phases, the number of ideas submitted by the people who contributed to those phases… you get the picture. We are constantly working to improve and evolve our influence engine. Back to the cooking metaphor: the ingredients may stay the same, but the recipe itself may vary from time to time.</p>
</div>

<div class="box-element">
<h4>Now let's talk about what you really wanna know: how the influence you earn on Quirky translates to cold, hard cash.</h4>
<p style="font-size:14px; color:#666666">For each product manufactured and sold, the Quirky community receives 30% of the total revenue generated by direct sales of the product on Quirky.com, as well as 10% of revenue from indirect sales (wholesale orders and worldwide retail sales). That share of product revenue is divided among all the community members that influenced the product, based on their corresponding influence percentage.</p>
</div>


</div>
</div>
</div>
</html>
